CREATE TABLE public.ETL_SGP_AULA_PLANO_AULA_DADOS_OK
(
	id                          INT8          NOT NULL GENERATED ALWAYS AS IDENTITY,
	AUL_ue_id					VARCHAR  (15) NOT NULL,
	AUL_disciplina_id			VARCHAR  (15) NOT NULL,
	AUL_turma_id				VARCHAR  (15) NOT NULL,
	AUL_tipo_calendario_id		INT8		  NOT NULL,
	AUL_professor_rf			VARCHAR  (15) NOT NULL,
	AUL_quantidade				INT8		  NOT NULL,
	AUL_data_aula				DATE    	  NOT NULL,
	AUL_recorrencia_aula		INT8		  NOT NULL,
	AUL_tipo_aula				INT8		  NOT NULL,
	AUL_criado_em				TIMESTAMP	  NOT NULL,
	AUL_criado_por				VARCHAR (200) NOT NULL,
	AUL_alterado_em				TIMESTAMP		  NULL,
	AUL_alterado_por			VARCHAR (200)	  NULL,
	AUL_criado_rf				VARCHAR  (15) NOT NULL,
	AUL_alterado_rf				VARCHAR  (15)     NULL,
	PLA_descricao				VARCHAR           NULL,
	PLA_desenvolvimento_aula	VARCHAR       NOT NULL,
	PLA_recuperacao_aula		VARCHAR           NULL,
	PLA_licao_casa				VARCHAR           NULL,
	SQL_tud_id					INT8		      NULL,
	SQL_tpc_id					INT8		      NULL,
	SQL_tau_id					INT8		      NULL,
	SQL_tur_id					INT8		      NULL,
	SQL_tur_codigoEOL			INT8		      NULL,
	SQL_esc_id					INT8		      NULL,
	SQL_esc_codigoEOL			VARCHAR  (20)     NULL
);