
version: "3"

services:
  prometheus:
    restart: always
    container_name: prom
    ports:
    - '9090:9090'
    volumes:
    - 'prometheus:/prometheus'
    - './configuracoes/prometheus.yml:/etc/prometheus/prometheus.yml'
    image: prom/prometheus
    user: root
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=3d
    networks:
    - sgp-network

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./configuracoes/prometheus_ds.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml
      - grafana:/var/lib/grafana
    networks:
    - sgp-network      
      
networks:
  sgp-network:

volumes:
  prometheus:
    driver: local
  grafana:
    driver: local