version: '3.1'

services:
  sme-redis:
    image: redis:5.0.5-alpine
    container_name: sme-redis
    ports:
      - "6379:6379"     
    networks:
      - sme-network  
  sme-workerservice:
    container_name: sme-workerservice
    image: sme-workerservice
    build:
      context: .
      dockerfile: ./src/SME.SGP.WorkerService/Dockerfile
    ports:
      - '5000:5000'    
    depends_on:
      - 'sme-redis'
    env_file:
      - sme-api.env
    networks:
      - sme-network        
networks:
  sme-network:
    driver: bridge
