version: '3.1'

volumes:
  grafana-data: {}
  postgres-data: {}
services:
  sme-api:
    container_name: sme-api
    image: sme-api
    build:
      context: .
      dockerfile: ./src/SME.SGP.Api/Dockerfile
    ports:
      - '8080:80'
    networks:
      - sme-network
    depends_on:
      - 'sme-db'
      - 'sme-redis'
    env_file:
      - sme-api.env
  sme-db:
    container_name: sme-db
    restart: always
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sgp_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sme-network
  sme-flyway:
    container_name: sme-flyway
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://sme-db:5432/sgp_db?user=postgres&password=postgres -locations='filesystem:/opt/scripts' -outOfOrder=true migrate
    volumes:
      - ./scripts:/opt/scripts
    depends_on:
      - 'sme-db'
    networks:
      - sme-network
  sme-webclient:
    container_name: sme-webclient
    image: sme-webclient
    build:
      context: .
      dockerfile: ./src/SME.SGP.WebClient/Dockerfile
    ports:
      - '80:80'
    networks:
      - sme-network
    depends_on:
      - 'sme-api'
    environment:
      - API_URL=http://localhost:8080/api
  grafana:
    container_name: sme-grafana
    restart: always
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - grafana-data:/var/lib/grafana
    networks:
      - sme-network
    depends_on:
      - 'prom'
  prom:
    container_name: sme-prometheus
    image: sme-prometheus
    build:
      context: .
      dockerfile: ./prometheus/Dockerfile
    ports:
      - 9090:9090
    networks:
      - sme-network
    depends_on:
      - 'sme-api'
  sme-redis:
    image: redis:5.0.5-alpine
    container_name: sme-redis
    ports:
      - '6379:6379'
    networks:
      - sme-network
networks:
  sme-network:
    driver: bridge
