version: "3"

services:
  
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sgp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: sgp/flyway
    build:
      dockerfile: build/Dockerfile.flyway
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    volumes:
      - ./scripts:/opt/scripts
    depends_on:
      postgres:
          condition: service_healthy
    command: -locations='filesystem:/opt/scripts' -outOfOrder=true migrate -X
    networks:
      - sgp-network

  redis:
    image: redis:6-alpine
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "--raw", "incr", "ping" ]
    ports:
      - '6379:6379'
    networks:
      - sgp-network

  minio:
    container_name: minio
    image: 'docker.io/bitnami/minio:2023.9.27'
    #command: server /data --address :9000 --console-address :9001
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - sgp-network
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DEFAULT_BUCKETS=temp:download,arquivos:download   
    volumes:
      - minio:/bitnami/minio/data
      
networks:
  sgp-network:

volumes:
  postgres:
    driver: local
  minio:
    driver: local