version: '3.1'

networks:
  sme-network:
    driver: bridge

volumes:
  minio-data:

services:
  sme-minio-server:
    container_name: sme-minio-server
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - sme-network
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DEFAULT_BUCKETS=bucket-temp-sgp:policy,bucket-sgp      
    volumes:
      - minio-data:/data