version: "3.1"

volumes:
  postgres-data: {}

services:
  postgres-db:
    container_name: postgres-db-testes
    restart: always
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
        - ./postgres:/docker-entrypoint-initdb.d/
    networks:
      - sme-network 
  mssql-db:
    container_name: mssql-db-testes
    restart: always
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SME@2021
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
        - ./mssql:/scripts/ 
    command:
      - /bin/bash
      - -c 
      - |
        # Launch MSSQL and send to background
        /opt/mssql/bin/sqlservr &
        # Wait 30 seconds for it to be available
        # (lame, I know, but there's no nc available to start prodding network ports)
        sleep 30
        # Run every script in /scripts
        # TODO set a flag so that this is only done once on creation, 
        #      and not every time the container runs
        for foo in /scripts/*.sql
          do /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -l 30 -e -i $$foo
        done
        # So that the container doesn't shut down, sleep this thread
        sleep infinity
      
networks:
  sme-network:
    driver: bridge
    name: sme_external_network
