export const Dados = {
  listaTiposConceitos: [],
  componentes: {
    tipoNota: 1,
    notas: [
      {
        nome: 'História',
        notaConceito: '10',
        notaPosConslelho: 1,
        conceitoPosConslelho: null,
        quantidadeAulas: 20,
        faltas: 2,
        ausenciasCompensadas: 0,
        frequencia: 90,
      },
      {
        nome: 'Lingua Inglesa',
        notaConceito: '9',
        notaPosConslelho: 10,
        conceitoPosConslelho: null,
        quantidadeAulas: 30,
        faltas: 2,
        ausenciasCompensadas: 1,
        frequencia: 95,
      },
      {
        nome: 'Arte',
        notaConceito: '10',
        notaPosConslelho: '',
        conceitoPosConslelho: '',
        quantidadeAulas: 20,
        faltas: 0,
        ausenciasCompensadas: 0,
        frequencia: 100,
      },
    ],
  },
  componentesRegencia: {
    tipoNota: 2,
    notas: [
      {
        nome: 'Lingua Inglesa',
        notaConceito: '9',
        notaPosConslelho: '',
        conceitoPosConslelho: '',
        quantidadeAulas: 30,
        faltas: 2,
        ausenciasCompensadas: 1,
        frequencia: 95,
      },
      {
        nome: 'Arte',
        notaConceito: '10',
        notaPosConslelho: '',
        conceitoPosConslelho: '',
        quantidadeAulas: 20,
        faltas: 0,
        ausenciasCompensadas: 0,
        frequencia: 100,
      },
    ],
  },
};
