export const Dados = {
  componentes: [
    {
      nome: 'História',
      notaConceito: '10',
      notaPosConslelho: '',
      quantidadeAulas: 20,
      faltas: 2,
      ausenciasCompensadas: 0,
      frequencia: 90,
    },
    {
      nome: 'Lingua Inglesa',
      notaConceito: '9',
      notaPosConslelho: '',
      quantidadeAulas: 30,
      faltas: 2,
      ausenciasCompensadas: 1,
      frequencia: 95,
    },
    {
      nome: 'Arte',
      notaConceito: '10',
      notaPosConslelho: '',
      quantidadeAulas: 20,
      faltas: 0,
      ausenciasCompensadas: 0,
      frequencia: 100,
    },
  ],
  componentesRegencia: [
    {
      nome: 'Lingua Inglesa',
      notaConceito: '9',
      notaPosConslelho: '',
      quantidadeAulas: 30,
      faltas: 2,
      ausenciasCompensadas: 1,
      frequencia: 95,
    },
    {
      nome: 'Arte',
      notaConceito: '10',
      notaPosConslelho: '',
      quantidadeAulas: 20,
      faltas: 0,
      ausenciasCompensadas: 0,
      frequencia: 100,
    },
  ],
};
