export const aulaDto = {
  alteradoEm: null,
  alteradoPor: null,
  alteradoRF: null,
  aulaCJ: false,
  criadoEm: '',
  criadoPor: '',
  criadoRF: '',
  dataAula: null,
  dentroPeriodo: true,
  disciplinaCompartilhadaId: null,
  disciplinaId: '',
  disciplinaNome: '',
  id: null,
  professorRf: '',
  quantidade: 1,
  recorrenciaAula: 1,
  somenteLeitura: false,
  tipoAula: 1,
  tipoCalendarioId: 17,
  turmaId: '',
  ueId: '',
};
