const RotasDto = {
  PRINCIPAL: '/',
  MEUS_DADOS: '/meus-dados',
  NOTIFICACOES: '/notificacoes',
  PLANO_CICLO: '/planejamento/plano-ciclo',
  PLANO_ANUAL: '/planejamento/plano-anual',
  ATRIBUICAO_SUPERVISOR_LISTA: '/gestao/atribuicao-supervisor-lista',
  ATRIBUICAO_ESPORADICA_LISTA: '/gestao/atribuicao-esporadica',
  ATRIBUICAO_CJ_LISTA: '/gestao/atribuicao-cjs',
  ATRIBUICAO_CJ_FORM: '/gestao/atribuicao-cjs/editar',
  REINICIAR_SENHA: '/usuarios/reiniciar-senha',
  TIPO_EVENTOS: '/calendario-escolar/tipo-eventos',
  PERIODOS_ESCOLARES: '/calendario-escolar/periodos-escolares',
  TIPO_CALENDARIO_ESCOLAR: '/calendario-escolar/tipo-calendario-escolar',
  TIPO_FERIADO: '/calendario-escolar/tipo-feriado',
  EVENTOS: '/calendario-escolar/eventos',
  CALENDARIO_ESCOLAR: '/calendario-escolar',
  CALENDARIO_PROFESSOR: '/calendario-escolar/calendario-professor',
  CALENDARIO_PROFESSOR_II: '/calendario-escolar/calendario-professor/v2',
  CADASTRO_DE_AULA: '/calendario-escolar/calendario-professor/cadastro-aula',
  CADASTRO_DE_AVALIACAO:
    '/calendario-escolar/calendario-professor/cadastro-avaliacao',
  FREQUENCIA_PLANO_AULA: '/diario-classe/frequencia-plano-aula',
  TIPO_AVALIACAO: '/configuracoes/tipo-avaliacao',
  NOTAS: '/diario-classe/notas',
  AULA_DADA_AULA_PREVISTA: '/diario-classe/aula-dada-aula-prevista',
  REGISTRO_POA: '/diario-classe/registro-poa',
  COMPENSACAO_AUSENCIA: '/diario-classe/compensacao-ausencia',
  FECHAMENTO_BIMESTRE: '/fechamento/fechamento-bimestre',
  PERIODO_FECHAMENTO_ABERTURA:
    '/calendario-escolar/periodo-fechamento-abertura',
  PAP: '/relatorios/pap/relatorio-graficos',
  PERIODO_FECHAMENTO_REABERTURA:
    '/calendario-escolar/periodo-fechamento-reabertura',
  RELATORIO_PAP_ACOMPANHAMENTO: '/relatorios/pap/relatorio-preenchimento',
  PENDENCIAS_FECHAMENTO: '/fechamento/pendencias-fechamento',
  ACOMPANHAMENTO_COMUNICADOS: '/gestao/acompanhamento-escolar/comunicados',
  CONSELHO_CLASSE: '/fechamento/conselho-classe',
  RELATORIO_SEMESTRAL: '/relatorios/pap/relatorio-semestral',
  SEM_PERMISSAO: '/sem-permissao',
  TERRITORIO_SABER: '/planejamento/plano-anual-territorio-saber',
  HISTORICO_ESCOLAR: '/relatorios/historico-escolar',
  RELATORIO_BOLETIM_SIMPLES: '/relatorios/diario-classe/boletim-simples',
  ATA_FINAL_RESULTADOS: '/relatorios/atas/ata-final-resultados',
  FALTAS_FREQUENCIA: '/relatorios/frequencia/faltas-frequencia',
  RELATORIO_PENDENCIAS: '/relatorios/pendencias-fechamento',
};

export default RotasDto;
