const RotasDto = {
  PRINCIPAL: '/',
  MEUS_DADOS: '/meus-dados',
  NOTIFICACOES: '/notificacoes',
  PLANO_CICLO: '/planejamento/plano-ciclo',
  PLANO_ANUAL: '/planejamento/plano-anual',
  ATRIBUICAO_SUPERVISOR_LISTA: '/gestao/atribuicao-supervisor-lista',
  ATRIBUICAO_ESPORADICA_LISTA: '/gestao/atribuicao-esporadica',
  ATRIBUICAO_CJ_LISTA: '/gestao/atribuicao-cjs',
  ATRIBUICAO_CJ_FORM: '/gestao/atribuicao-cjs/editar',
  REINICIAR_SENHA: '/usuarios/reiniciar-senha',
  TIPO_EVENTOS: '/calendario-escolar/tipo-eventos',
  PERIODOS_ESCOLARES: '/calendario-escolar/periodos-escolares',
  TIPO_CALENDARIO_ESCOLAR: '/calendario-escolar/tipo-calendario-escolar',
  TIPO_FERIADO: '/calendario-escolar/tipo-feriado',
  EVENTOS: '/calendario-escolar/eventos',
  CALENDARIO_ESCOLAR: '/calendario-escolar',
  CALENDARIO_PROFESSOR: '/calendario-escolar/calendario-professor',
  CALENDARIO_PROFESSOR_II: '/calendario-escolar/calendario-professor/v2',
  CADASTRO_DE_AULA: '/calendario-escolar/calendario-professor/cadastro-aula',
  CADASTRO_DE_AVALIACAO:
    '/calendario-escolar/calendario-professor/cadastro-avaliacao',
  FREQUENCIA_PLANO_AULA: '/diario-classe/frequencia-plano-aula',
  ACOMPANHAMENTO_FREQUENCIA: '/diario-classe/acompanhamento-frequencia',
  TIPO_AVALIACAO: '/configuracoes/tipo-avaliacao',
  NOTAS: '/diario-classe/notas',
  AULA_DADA_AULA_PREVISTA: '/diario-classe/aula-dada-aula-prevista',
  REGISTRO_POA: '/diario-classe/registro-poa',
  COMPENSACAO_AUSENCIA: '/diario-classe/compensacao-ausencia',
  FECHAMENTO_BIMESTRE: '/fechamento/fechamento-bimestre',
  PERIODO_FECHAMENTO_ABERTURA:
    '/calendario-escolar/periodo-fechamento-abertura',
  PAP: '/relatorios/pap/relatorio-graficos',
  PERIODO_FECHAMENTO_REABERTURA:
    '/calendario-escolar/periodo-fechamento-reabertura',
  RELATORIO_PAP_ACOMPANHAMENTO: '/relatorios/pap/relatorio-preenchimento',
  PENDENCIAS_FECHAMENTO: '/fechamento/pendencias-fechamento',
  ACOMPANHAMENTO_COMUNICADOS: '/gestao/acompanhamento-escolar/comunicados',
  CONSELHO_CLASSE: '/fechamento/conselho-classe',
  RELATORIO_SEMESTRAL: '/relatorios/pap/relatorio-semestral',
  SEM_PERMISSAO: '/sem-permissao',
  TERRITORIO_SABER: '/planejamento/plano-anual-territorio-saber',
  HISTORICO_ESCOLAR: '/relatorios/historico-escolar',
  RELATORIO_BOLETIM_SIMPLES: '/relatorios/diario-classe/boletim-simples',
  ATA_FINAL_RESULTADOS: '/relatorios/atas/ata-final-resultados',
  FALTAS_FREQUENCIA: '/relatorios/frequencia/faltas-frequencia',
  DIARIO_BORDO: '/diario-classe/diario-bordo',
  RELATORIO_PENDENCIAS: '/relatorios/pendencias-fechamento',
  CARTA_INTENCOES: '/planejamento/carta-intencoes',
  RELATORIO_PARECER_CONCLUSIVO: '/relatorios/parecer-conclusivo',
  RELATORIO_NOTAS_CONCEITOS_FINAIS: '/relatorios/notas-conceitos-finais',
  RELATORIO_COMPENSACAO_AUSENCIA: '/relatorios/compensacao-ausencia',
  DEVOLUTIVAS: '/diario-classe/devolutiva',
  REGISTRO_INDIVIDUAL: '/diario-classe/registro-individual',
  CONTROLE_GRADE: '/relatorios/diario-classe/controle-grade',
  RELATORIO_PLANEJAMENTO_DIARIO:
    '/relatorios/diario-classe/planejamento-diario',
  POC_EDITOR: '/editor',
  SONDAGEM: '/sondagem',
  POC_UPLOAD_ARQUIVOS: '/upload-arquivos',
  HISTORICO_NOTIFICACOES: '/relatorios/notificacoes/historico-notificacoes',
  DOCUMENTOS_PLANOS_TRABALHO: '/gestao/documentos-planos-trabalho',
  RELATORIO_USUARIOS: '/relatorios/gestao/usuarios',
  RELATORIO_ATRIBUICAO_CJ: '/relatorios/gestao/atribuicao-cj',
  RELATORIO_ALTERACAO_NOTAS: '/relatorios/fechamento/historico-alteracao-notas',
  RELATORIO_LEITURA: '/relatorios/escola-aqui/leitura',
  RELATORIO_ESCOLA_AQUI_ADESAO: '/relatorios/escola-aqui/adesao',
  RELATORIO_AEE_ENCAMINHAMENTO: '/aee/encaminhamento',
  OCORRENCIAS: '/gestao/ocorrencias',
  RELATORIO_AEE_REGISTRO_ITINERANCIA: '/aee/registro-itinerancia',
  RELATORIO_AEE_PLANO: '/aee/plano',
  ACOMPANHAMENTO_APRENDIZAGEM: '/fechamento/acompanhamento-aprendizagem',
  RELATORIO_DEVOLUTIVAS: '/relatorios/planejamento/devolutivas',
  DASHBOARD_ESCOLA_AQUI: '/dashboard/escola-aqui',
  DASHBOARD_AEE: '/dashboard/aee',
  DASHBOARD_REGISTRO_ITINERANCIA: '/dashboard/registro-itinerancia',
  DASHBOARD_FREQUENCIA: '/dashboard/frequencia',
};

export default RotasDto;
