const tipoEvento = {
  ConselhoDeClasse: 1,
  EventoDRE: 2,
  FechamentoBimestre: 3,
  Feriado: 4,
  FeriasDocentes: 5,
  LiberacaoExcepcional: 6,
  LiberacaoBoletim: 7,
  OrganizacaoEscolar: 8,
  Outros: 9,
  ProjetoPoliticoPedagogico: 10,
  Recesso: 11,
  RecreioNasFerias: 12,
  ReposicaoDeAula: 13,
  ReposicaoDoDia: 14,
  ReposicaoNoRecesso: 15,
  ReuniaoPedagogica: 16,
  ReuniaoAPM: 17,
  ReuniaoConselhoEscola: 18,
  ReuniaoResponsaveis: 19,
  Sondagem: 20,
  SuspensaoAtividades: 21,
  Formacao: 22,
  Curso: 23,
  EncontroMensal: 24,
  Seminario: 25,
  Palestra: 26,
  Reuniao: 27,
};

export default tipoEvento;
