USE [Manutencao]

INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(1,94765,1, 'MAXIMO DE MOURA SANTOS, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(2,16993,2, 'VICENTE AMATO SOBRINHO, COM. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(3,19404,2, 'NEUZA AVELINO DA SILVA MELO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(4,93866,2, 'RAIMUNDO CORREIA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(5,19503,2, 'JARDIM BARTIRA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(6,108,2, 'JOSE ERMIRIO DE MORAIS, SEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(7,93891,2, 'ARMANDO CRIDEY RIGHETTI ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(8,19226,2, 'MARIA CLARA MACHADO ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(9,19410,2, 'MURURES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(10,93904,2, 'CAPISTRANO DE ABREU ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(11,93831,2, 'ANTONIA E ARTUR BEGBIE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(12,93882,2, 'JOSE BENTO DE ASSIS, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(13,19225,2, 'WANDA OVIDIO GONCALVES, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(14,14583,2, 'FLAVIO AUGUSTO ROSA, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(15,99139,2, 'VIRGILIO DE MELLO FRANCO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(16,93912,2, 'CARLOS PASQUALE, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(17,19505,2, 'JOSE MARIO PIRES AZANHA, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(18,93696,2, 'EPITACIO PESSOA, PRES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(19,93742,2, 'LUIS SAIA, ARQ. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(20,93769,2, 'PEDRO DE FRONTIN, ALM. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(21,93823,2, 'HENRIQUE FELIPE DA COSTA - HENRICAO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(22,93840,2, 'NEWTON REIS, GEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(23,93874,2, 'JOSE AMERICO DE ALMEIDA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(24,93939,2, 'SUD MENNUCCI ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(25,10049,2, 'CHICO FALCONI, PE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(26,19367,2, 'TRES PONTES ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(27,19409,2, 'IZABEL APARECIDA CRISTOVAO DA LUZ, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(28,19449,2, 'JURANDI GOMES DE ARAUJO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(29,19507,2, 'PEDRO FUKUYEI YAMAGUCHI FERREIRA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(30,93700,2, 'RAUL PILLA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(31,93858,2, 'MARIA IMILDA DO SANTISSIMO SACRAMENTO, ME. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(32,19433,2, 'JOSEFA NICACIO ARAUJO, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(33,19011,2, 'LINO DE MATTOS, SEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(34,93726,2, 'PEDRO TEIXEIRA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(35,18210,2, 'DARCY RIBEIRO ',3, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(36,93921,2, 'EZEQUIEL RAMOS JUNIOR ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(37,93751,2, 'PAULO ROLIM LOUREIRO, D. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(38,15440,2, 'EUZEBIO ROCHA FILHO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(39,93807,2, 'JOAO AUGUSTO BREVES, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(40,19269,2, 'PARQUE SAO CARLOS ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(41,19400,2, 'DAMA ENTRE RIOS VERDES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(42,19426,2, 'MARISA MORETTI CAMARA, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(43,97713,2, 'JOSE PEDRO LEITE CORDEIRO, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(44,10405,2, 'NILDO DO AMARAL JUNIOR, PE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(45,93777,2, 'FERNANDO DE AZEVEDO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(46,93734,2, 'ANTONIO CARLOS DE ANDRADA E SILVA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(47,19506,2, 'MILTON PEREIRA COSTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(48,19278,2, 'VILA CURUCA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(49,99651,2, 'JOSE HONORIO RODRIGUES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(50,19241,2, 'HELLIO TAVARES, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(51,93688,2, 'PEDRO ALEIXO, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(52,19529,2, 'JARDIM SILVA TELES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(53,93793,2, 'JOSE DE ANCHIETA, PE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(54,95265,3, 'ARMANDO ARRUDA PEREIRA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(55,95257,3, 'ANTONIO DE SAMPAIO DORIA, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(56,93211,3, 'JOAO GUALBERTO DO AMARAL CARVALHO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(57,93203,3, 'LAERTE RAMOS DE CARVALHO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(58,10120,3, 'CARLOS AUGUSTO DE QUEIROZ ROCHA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(59,418,3, 'JOAO DE SOUZA FERRAZ, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(60,93271,3, 'TIRADENTES, ALF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(61,10111,3, 'MARIO SCHONBERG, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(62,19465,3, 'AMELIA RODRIGUES DE OLIVEIRA, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(63,264,3, 'SYLVIO HECK, ALM. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(64,10138,3, 'ELZA MAIA COSTA FREIRE, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(65,95206,3, 'CALOGERAS, MIN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(66,95273,3, 'CACILDA BECKER ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(67,93289,3, 'PEREIRA CARNEIRO, CDE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(68,93262,3, 'ISABEL VIEIRA FERREIRA, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(69,93190,3, 'CARLOS DE ANDRADE RIZZINI ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(70,93181,3, 'LINNEU PRESTES, PROF. ',3, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(71,93220,3, 'ANTONIO CARLOS DE ABREU SODRE, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(72,95249,3, 'HABIB CARLOS KYRILLOS, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(73,19257,3, 'ALDO DA TOFORI, PE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(74,93246,3, 'MANOEL CARLOS DE FIGUEIREDO FERRAZ, DES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(75,93254,3, 'JOAO SUSSUMU HIRATA, DEP. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(76,15423,3, 'PRESTES MAIA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(77,19419,3, 'ANA MARIA ALVES BENETTI, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(78,93238,3, 'ANTENOR NASCENTES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(79,99180,3, 'ANNE SULLIVAN ',4, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(80,19420,3, 'MARIA LUCIA DOS SANTOS, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(81,95231,3, 'MARINA VIEIRA DE CARVALHO MESQUITA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(82,19260,3, 'PAULO GONCALO DOS SANTOS, PROF. ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(83,95222,3, 'ARY PARREIRAS, ALM. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(84,19373,3, 'JOSE REZENDE, PROF. ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(85,95281,3, 'NELSON PIMENTEL QUEIROZ, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(86,93157,3, 'CHIQUINHA RODRIGUES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(87,95214,3, 'BERNARDO O HIGGINS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(88,93173,3, 'JOAQUIM CANDIDO DE AZEVEDO MARQUES, DES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(89,19196,3, 'LILIANE VERZINI SILVA, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(90,92771,4, 'SOLANO TRINDADE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(91,92681,4, 'JOSE DE ALCANTARA MACHADO FILHO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(92,92797,4, 'JULIO MESQUITA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(93,19551,4, 'CESAR ARRUDA CASTANHO, DEP. ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(94,92801,4, 'IBRAHIM NOBRE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(95,92827,4, 'ALVARO SILVA BRAGA, GEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(96,92711,4, 'DEODORO DA FONSECA, MAL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(97,19417,4, 'JARDIM PAULO VI ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(98,19416,4, 'VILA MUNCK ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(99,99287,4, 'VIANNA MOOG ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(100,92843,4, 'ROBERTO MANGE, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(101,92738,4, 'TARSILA DO AMARAL ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(102,92720,4, 'ARTHUR WHITAKER, DES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(103,92789,4, 'LUIZ EDUARDO MATARAZZO, CDE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(104,99589,4, 'PEDRO NAVA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(105,92690,4, 'AMORIM LIMA, DES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(106,92851,4, 'EUCLYDES DE OLIVEIRA FIGUEIREDO, GEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(107,92762,4, 'JOAO XXIII ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(108,92746,4, 'ALIPIO ANDRADA SERPA, TTE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(109,93149,4, 'OLAVO PEZZOTTI, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(110,92703,4, 'THEODOMIRO DIAS, DES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(111,93165,4, 'JOSE DIAS DA SILVEIRA, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(112,191,4, 'ALIPIO CORREA NETO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(113,11924,4, 'MARIA ALICE BORGES GHION, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(114,19249,4, 'DAISY AMADIO FUJIWARA, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(115,19262,4, 'BUTANTA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(116,92819,4, 'BRASIL-JAPAO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(117,92754,4, 'ALCIDES GONCALVES ETCHEGOYEN, GEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(118,19160,4, 'ILEUSA CAETANO DA SILVA, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(119,99261,4, 'TEOFILO BENEDITO OTTONI ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(120,93131,4, 'MARIA ANTONIETA D ALKIMIN BASTO, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(121,97047,4, 'EDUCANDARIO DOM DUARTE, ANEXA AO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(122,477,4, 'EDA TEREZINHA CHICA MEDEIROS, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(123,93548,5, 'SATURNINO PEREIRA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(124,19369,5, 'LAJEADO ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(125,8834,5, 'IDEMIA DE GODOY, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(126,93530,5, 'JOANA ANGELICA DE JESUS, MADRE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(127,17973,5, 'MAILSON DELANE, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(128,14699,5, 'ANTONIO DAVILA, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(129,16527,5, 'CLAUDIA BARTOLOMAZI, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(130,9148,5, 'ALEXANDRE VANNUCHI LEME ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(131,93637,5, 'OSWALDO ARANHA BANDEIRA DE MELLO ',3, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(132,19476,5, 'MARIA APARECIDA DO NASCIMENTO, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(133,93513,5, 'JOAO DE LIMA PAIVA, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(134,19437,5, 'DIAS GOMES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(135,93653,5, 'VLADIMIR HERZOG ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(136,13528,5, 'ANNA LAMBERGA ZEGLIO, VER. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(137,19456,5, 'HELINA COUTINHO LOURENCO ALVES, PROFESSORA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(138,93645,5, 'MAURICIO GOULART ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(139,19208,5, 'LUIZ ROBERTO MEGA, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(140,19457,5, 'MARIA APARECIDA MAGNANELLI FERNANDES, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(141,93785,5, 'JOAO RIBEIRO DE BARROS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(142,93815,5, 'ALEXANDRE DE GUSMAO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(143,97055,5, 'JUSCELINO KUBITSCHEK DE OLIVEIRA, PRES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(144,97721,5, 'JOSE AUGUSTO CESAR SALGADO, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(145,9156,5, 'LUIS CARLOS PRESTES, SEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(146,12157,5, 'ELIAS SHAMMASS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(147,19443,5, 'MEIRE DE JESUS RIBEIRO,PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(148,19455,5, 'CELIA REGINA ANDERY BRAGA, PROF ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(149,93521,5, 'VINTE E CINCO DE JANEIRO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(150,19265,5, 'JAMBEIRO ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(151,19264,5, 'INACIO MONTEIRO ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(152,13510,5, 'OLINDA MENEZES SERRA VIDAL, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(153,10413,5, 'QUIRINO CARNEIRO RENNO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(154,97705,5, 'AURELIANO LEITE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(155,15024,5, 'CAIO SERGIO POMPEU DE TOLEDO, DEP. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(156,97063,5, 'ANTONIO PEREIRA IGNACIO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(157,19333,5, 'AGUA AZUL ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(158,19447,5, 'JOEL FERNANDES DE SOUZA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(159,19453,6, 'MARIO PEREIRA BICUDO, PROF. ',4, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(160,19363,6, 'JARDIM PAULISTANO ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(161,94251,6, 'SEBASTIAO NOGUEIRA DE LIMA, DES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(162,99783,6, 'GERALDO SESSO JUNIOR ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(163,19402,6, 'ZILKA SALABERRY DE CARVALHO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(164,94315,6, 'PEDRO AMERICO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(165,19350,6, 'JOSE HERMINIO RODRIGUES, CEL. PM ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(166,94277,6, 'JOAO AMOS COMENIUS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(167,94161,6, 'NILO PECANHA, PRES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(168,94366,6, 'GARCIA DAVILA, CTE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(169,19704,6, 'PRIMO PASCOLI MELARE, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(170,19394,6, 'CAIRA ALAYDE ALVARENGA MEDEA, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(171,94293,6, 'OSVALDO QUIRINO SIMOES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(172,94200,6, 'MILTOM CAMPOS, SEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(173,91804,6, 'PAULO NOGUEIRA FILHO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(174,94226,6, 'RAUL FERNANDES, EMB. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(175,19395,6, 'NEIR AUGUSTO LOPES, PROF ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(176,94323,6, 'ELIAS DE SIQUEIRA CAVALCANTI, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(177,94692,6, 'MARCILIO DIAS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(178,94218,6, 'ANDRE RODRIGUES DE ALCKMIN, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(179,94382,6, 'CECILIA MORAES DE VASCONCELOS, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(180,94307,6, 'FREDERICO GUSTAVO DOS SANTOS, TTE. AVIADOR ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(181,19458,6, 'MARIA APARECIDA RODRIGUES CINTRA, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(182,19349,6, 'JARDIM DAMASCENO I ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(183,299,6, 'ROBERTO PATRICIO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(184,94331,6, 'HUMBERTO DANTAS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(185,19405,6, 'GILBERTO DUPAS, PROF ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(186,19462,6, 'LILIAN MASO, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(187,94374,6, 'TEOTONIO VILELA, SEN. ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(188,94269,6, 'CASTRO ALVES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(189,94188,6, 'JOANINHA GRASSI FAGUNDES, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(190,94196,6, 'ERICO VERISSIMO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(191,94170,6, 'PLINIO AYROSA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(192,94340,6, 'AROLDO DE AZEVEDO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(193,94234,6, 'THEO DUTRA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(194,19341,6, 'JARDIM GUARANI - JOSE ALFREDO APOLINARIO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(195,94242,6, 'ANTONIO PRUDENTE, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(196,94358,6, 'ANGELINA MAFFEI VITA, DA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(197,19365,7, 'ROSANGELA RODRIGUES VIEIRA, PROFA. ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(198,94005,7, 'HUMBERTO DE CAMPOS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(199,94137,7, 'CECILIA MEIRELES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(200,93980,7, 'FIRMINO TIBURCIO DA COSTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(201,93955,7, 'JACKSON DE FIGUEIREDO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(202,19399,7, 'JANUARIO MANTELLI NETO, DEP. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(203,93947,7, 'OTHELO FRANCO, GEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(204,94081,7, 'HENRIQUE PEGADO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(205,93661,7, 'OCTAVIO MANGABEIRA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(206,94099,7, 'JUAREZ TAVORA, MAL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(207,329,7, 'NEUSA BASSETTO, PROFA. ',4, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(208,95362,7, 'MAUA, BR. DE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(209,94153,7, 'ARTHUR AZEVEDO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(210,94048,7, 'ANTONIO VIEIRA, PE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(211,94129,7, 'GUILHERME DE ALMEIDA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(212,94145,7, 'EDGARD CAVALHEIRO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(213,95087,7, 'SILVIO FLEMING, MJ. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(214,11851,7, 'ANALIA FRANCO BASTOS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(215,19396,7, 'SERAFIN MARTINEZ GUTIERREZ, PE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(216,93963,7, 'JOAO PINHEIRO, PRES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(217,94102,7, 'FRANCISCO DE MONT ALVERNE, FREI ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(218,94111,7, 'LUIS WASHINGTON VITA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(219,93998,7, 'ABRAO DE MORAES, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(220,94021,7, 'CAIRU, VISC. DE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(221,15296,7, 'JOAO FRANZOLIN NETO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(222,93670,7, 'AMADEU AMARAL ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(223,94013,7, 'JOSE BONIFACIO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(224,94072,7, 'WANNY SALGADO ROCHA, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(225,485,7, 'ASSAD ABDALA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(226,94056,7, 'JENNY GOMES, DA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(227,94641,7, 'HENRIQUE, INFANTE D. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(228,15121,7, 'JOSE CARLOS DE FIGUEIREDO FERRAZ, PREF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(229,19418,7, 'ALEX MARTINS COSTA, PROF, MAESTRO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(230,95109,7, 'LEONOR MENDES DE BARROS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(231,95079,7, 'FABIO DA SILVA PRADO, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(232,93971,7, '19 DE NOVEMBRO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(233,95095,7, 'EMILIANO DI CAVALCANTI ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(234,19388,7, 'ANTONIO CARLOS ROCHA, PROF. ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(235,94030,7, 'ARTHUR ALVIM ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(236,95125,8, 'BARTOLOMEU LOURENCO DE GUSMAO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(237,19143,8, 'JOSE QUERINO RIBEIRO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(238,19398,8, 'AGUAS DE MARCO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(239,93718,8, 'ANTONIO DUARTE DE ALMEIDA, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(240,10103,8, 'FRANCISCO ALVES MENDES FILHO - CHICO MENDES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(241,93467,8, 'DANYLO JOSE FERNANDES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(242,94064,8, '8 DE MAIO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(243,19386,8, 'MARIA APARECIDA DE SOUZA CAMPOS, PROFA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(244,95133,8, 'JOAO NAOKI SUMITA, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(245,17523,8, 'CLOTILDE ROSA HENRIQUES ELIAS, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(246,93505,8, 'BENEDITO CALIXTO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(247,93629,8, 'AURELIO ARROBAS MARTINS, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(248,95150,8, 'ROQUETTE PINTO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(249,95192,8, 'GUIMARAES ROSA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(250,19691,8, 'MARIO COVAS, GOV. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(251,93459,8, 'EDUARDO PRADO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(252,93475,8, 'AYRES MARTINS TORRES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(253,95117,8, 'KENNEDY, PRES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(254,95184,8, 'SERGIO MILLIET ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(255,93432,8, 'CORREIA DE MELLO, BRIG. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(256,8842,8, 'SEBASTIAO FRANCISCO, O NEGRO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(257,19261,8, 'PAULO GOMES CARDIM, PROF. DR. ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(258,95141,8, 'VICENTINA RIBEIRO DA LUZ ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(259,19227,8, 'CONCEICAO APARECIDA DE JESUS, PROFA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(260,93441,8, 'CARLOS CHAGAS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(261,99678,8, 'MALLET, MAL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(262,93491,8, 'ARTUR NEIVA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(263,19397,8, 'GILMAR TACCOLA , PROF ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(264,15130,8, 'JULIO CESAR DE MELO E SOUSA-MALBA TAHAN, PROF ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(265,93483,8, 'HAROLDO VELOSO, BRIG. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(266,94919,1, 'LOURENCO FILHO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(267,94897,1, 'OCTAVIO PEREIRA LOPES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(268,19401,1, 'JARDIM FONTALIS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(269,99091,1, 'HIPOLITO JOSE DA COSTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(270,94811,1, 'ROMAO GOMES, CEL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(271,94714,1, 'NOE AZEVEDO, PROF ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(272,19488,1, 'PAULO CARNEIRO THOMAZ ALVES, GAL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(273,302,1, 'HELIO FRANCO CHAVES, CEL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(274,94706,1, 'GASTAO MOUTINHO, CTE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(275,19046,1, 'CELIA REGINA LEKEVICIUS CONSOLIN, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(276,94668,1, 'DERVILLE ALLEGRETTI, PROF. ',3, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(277,94757,1, 'RONDON, MAL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(278,94749,1, 'MARTIN FRANCISCO RIBEIRO DE ANDRADA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(279,94862,1, 'ALBERTO SANTOS DUMONT ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(280,94927,1, 'MARIA HELENA FARIA LIMA, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(281,94901,1, 'EDSON RODRIGUES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(282,94790,1, 'HELENA LOMBARDI BRAGA, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(283,94820,1, 'JOAO DOMINGUES SAMPAIO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(284,17442,1, 'ANTONIO SAMPAIO, VER. ',3, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(285,94684,1, 'MARCOS MELEGA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(286,94773,1, 'OLIVA IRENE BAYERLEIN SILVA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(287,94838,1, 'PEDRO I, D. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(288,94854,1, 'ENEAS CARVALHO DE AGUIAR ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(289,94943,1, 'RODRIGUES ALVES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(290,94846,1, 'TAMANDARE, ALM. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(291,94951,1, 'SHIRLEY GUIO, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(292,94803,1, 'ARY GOMES, CEL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(293,94871,1, 'JULIO MARCONDES SALGADO, GEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(294,94731,1, 'ESMERALDA SALLES PEREIRA RAMOS, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(295,94889,1, 'ANTONIO SANT ANA GALVAO, FREI ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(296,19631,1, 'NILCE CRUZ FIGUEIREDO, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(297,337,1, 'LUCIE BRAY, ME ',4, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(298,94935,1, 'FRANKLIN AUGUSTO DE MOURA CAMPOS, PROF ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(299,94285,1, 'RAUL DE LEONI ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(300,94676,1, 'ADOLPHO OTTO DE LAET, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(301,94722,1, 'JOAO RAMOS - PERNAMBUCO - ABOLICIONISTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(302,19337,1, 'JACANA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(303,94781,1, 'RUY BARBOSA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(304,95559,9, 'CLAUDIO MANOEL DA COSTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(305,19454,9, 'BARTOLOMEU CAMPOS DE QUEIROS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(306,93564,9, 'JOAQUIM OSORIO DUQUE ESTRADA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(307,93581,9, 'PLINIO DE QUEIROZ ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(308,19640,9, 'MARIA LISBOA DA SILVA, PROFA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(309,19216,9, 'THEREZA MACIEL DE PAULA PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(310,93572,9, 'COELHO NETO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(311,19366,9, 'TATIANA BELINKY ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(312,95516,9, 'HERALDO BARBUY ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(313,19223,9, 'MARIA APARECIDA VILASBOAS, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(314,19407,9, 'VIRGINIA LORISA ZEITOUNIAN CAMARGO, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(315,95494,9, 'ARMANDO DE SALLES OLIVEIRA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(316,19274,9, 'CANDIDA DORA PINO PRETINI, PROFA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(317,95524,9, 'VINICIUS DE MORAES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(318,19232,9, 'FAZENDA DA JUTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(319,95176,9, 'JOSE LINS DO REGO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(320,95168,9, 'ACHILLES DE OLIVEIRA RIBEIRO, DES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(321,92622,9, 'ARLINDO CAETANO FILHO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(322,93602,9, 'RODRIGO MELLO FRANCO DE ANDRADE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(323,95508,9, 'BRASILIO MACHADO NETO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(324,95532,9, 'RODRIGUES DE CARVALHO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(325,95541,9, 'OLIVAL COSTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(326,95567,9, 'ALCEU AMOROSO LIMA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(327,95583,9, 'GREGORIO WESTRUPP, PE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(328,95591,9, 'IVETE VARGAS, DEP. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(329,95613,9, 'PAULO DUARTE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(330,18511,9, 'CARLOS CORREA MASCARO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(331,19244,9, 'GIUSEPPE TAVOLARO, PROF ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(332,19391,9, 'ALTO ALEGRE ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(333,93556,9, 'FELICIO PAGLIUSO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(334,99121,9, 'DOMINGOS RUBINO, PROF. ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(335,13803,9, 'JULIO DE GRAMMONT ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(336,16519,9, 'RUBENS PAIVA ',3, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(337,19460,9, 'JOSE CARLOS NICOLETO - ZITO, PROFESSOR ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(338,95575,9, 'CIDADE DE OSAKA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(339,99660,9, 'AMELIA, IMP. DA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(340,93599,9, 'JOSE MARIA WHITAKER ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(341,19425,9, 'MARTIN LUTHER KING JR ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(342,95460,9, 'EMILIO RIBAS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(343,892,9, 'HENRIQUE SOUZA FILHO - HENFIL ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(344,99325,9, 'BENEDITO MONTENEGRO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(345,95605,9, 'VILANOVA ARTIGAS, ARQ. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(346,99792,9, 'FORTE DOS REIS MAGOS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(347,19408,9, 'PARQUE BOA ESPERANCA II ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(348,19615,9, 'DIRCE GENESIO DOS SANTOS, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(349,93611,9, 'RIVADAVIA MARQUES JUNIOR, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(350,19509,9, 'ACLAMADO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(351,12874,9, 'BENEDITO DE JESUS BATISTA LAURINDO - PE BATISTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(352,95443,9, 'HENRIQUE MELEGA, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(353,95478,9, 'FLORES DA CUNHA, DEP. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(354,95451,9, 'TAUNAY, VISC. DE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(355,19585,9, 'WLADIMIR DE TOLEDO PIZA,PREF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(356,19221,9, 'JARDIM DAS LARANJEIRAS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(357,95320,10, 'IRINEU MARINHO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(358,95401,10, 'PRUDENTE DE MORAIS, PRES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(359,94960,10, 'JOSE MARIA LISBOA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(360,95036,10, 'LEAO MACHADO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(361,95397,10, 'MARLENE RONDELLI, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(362,91812,10, 'HELEN KELLER ',4, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(363,19427,10, 'HERCILIA DE CAMPOS COSTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(364,95010,10, 'CASSIANO RICARDO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(365,94994,10, 'OLAVO FONTOURA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(366,19569,10, 'ROBERTO PLINIO COLACIOPPO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(367,94625,10, 'CAXIAS, DUQUE DE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(368,94633,10, 'CELSO LEITE RIBEIRO FILHO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(369,95001,10, 'JOAQUIM NABUCO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(370,95028,10, 'JOSE DO PATROCINIO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(371,95061,10, 'FRANCISCO MEIRELLES, DES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(372,95346,10, 'QUEIROZ FILHO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(373,95389,10, 'AUREA RIBEIRO XAVIER LOPES, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(374,95427,10, 'ALVARES DE AZEVEDO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(375,9971,10, 'LUIZ GONZAGA DO NASCIMENTO JR. - GONZAGUINHA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(376,19385,10, 'MARA CRISTINA TARTAGLIA SENA, PROFA. ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(377,95435,10, 'ALTINO ARANTES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(378,95371,10, 'CLEOMENES CAMPOS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(379,94978,10, 'EURICO GASPAR DUTRA, MAL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(380,95338,10, 'RUTH LOPES ANDRADE, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(381,95354,10, 'OSORIO, GEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(382,11533,10, 'FRANCISCO DA SILVEIRA BUENO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(383,95311,10, 'JEAN MERMOZ ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(384,94617,10, 'FARIA LIMA, BRIG. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(385,94986,10, 'SYLVIA MARTIN PIRES, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(386,19266,10, 'MENINOS ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(387,95052,10, 'ANTONIO DE ALCANTARA MACHADO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(388,17981,10, 'PERICLES EUGENIO DA SILVA RAMOS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(389,95044,10, 'CAMPOS SALLES, PRES. ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(390,19480,10, 'ABRAO HUCK, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(391,95303,10, 'MANOEL DE PAIVA, PE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(392,95290,10, 'JOAO CARLOS DA SILVA BORGES, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(393,95419,10, 'MASCARENHAS DE MORAES, MAL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(394,19414,11, 'MOISES ELIAS DE SOUZA, TTE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(395,19020,11, 'JAIRO DE ALMEIDA, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(396,19351,11, 'MARILI DIAS, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(397,540,11, 'RAUL POMPEIA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(398,94463,11, 'LEONEL FRANCA, PE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(399,94552,11, 'AMADEU MENDES, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(400,94579,11, 'JOSE FERRAZ DE CAMPOS, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(401,19195,11, 'JOSE KAUFFMANN , DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(402,94501,11, 'PAULO PRADO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(403,19322,11, 'CITY JARAGUA IV ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(404,19219,11, 'ENZO ANTONIO SILVESTRIN, PROF ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(405,19220,11, 'MARIO LAGO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(406,19413,11, 'ELIANE BENUTE LESSA AYRES GONCALVES, PROFESSORA- NANY BENUTE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(407,10171,11, 'ALDO RIBEIRO LUZ, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(408,94412,11, 'GABRIEL PRESTES, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(409,93106,11, 'DILERMANDO DIAS DOS SANTOS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(410,94544,11, 'RUI BLOEM ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(411,94421,11, 'LIBERATO BITTENCOURT, GEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(412,94404,11, 'MONTEIRO LOBATO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(413,94471,11, 'LUIZ DAVID SOBRINHO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(414,94391,11, 'MARIO KOSEL FILHO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(415,19277,11, 'VILA ATLANTICA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(416,19390,11, 'JAGUARE ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(417,92835,11, 'ESPIRIDIAO ROSAS, MAL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(418,94561,11, 'EUCLIDES CUSTODIO DA SILVEIRA, DES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(419,94595,11, 'SILVIO PORTUGAL, DES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(420,93122,11, 'JOSE MARIA PINTO DUARTE, TTE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(421,19271,11, 'PERA MARMELO ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(422,94536,11, 'JAIRO RAMOS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(423,94447,11, 'RENATO ANTONIO CHECCHIA, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(424,19412,11, 'BADRA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(425,19463,11, 'ESTACAO JARAGUA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(426,94510,11, 'HENRIQUE RAYMUNDO DYOTT FONTENELLE, BRIG. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(427,19487,11, 'CHACARA TURISTICA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(428,19607,11, 'ANTONIO RODRIGUES DE CAMPOS, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(429,93114,11, 'ANIBAL FREIRE, MIN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(430,94439,11, 'LEOPOLDINA, IMP. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(431,94480,11, 'JULIO DE OLIVEIRA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(432,94528,11, 'HENRIQUE GEISEL, GEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(433,16497,11, 'FERNANDO GRACIOSO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(434,19217,11, 'RECANTO DOS HUMILDES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(435,19224,11, 'MILENA BENEDICTO, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(436,19229,11, 'JOSUE DE CASTRO, PROF ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(437,19272,11, 'PERUS ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(438,19415,11, 'ALICE MEIRELLES REIS, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(439,94587,11, 'GABRIEL SYLVESTRE TEIXEIRA DE CARVALHO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(440,19445,11, 'ROGE FERREIRA, DEP. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(441,19389,11, 'PARQUE ANHANGUERA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(442,19314,11, 'PHILO GONCALVES DOS SANTOS, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(443,19218,11, 'JARDIM MONTE BELO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(444,14249,11, 'ERNESTO DE MORAES LEME, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(445,19215,11, 'REMO RINALDI NADDEO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(446,94609,11, 'ANTONIO ALVES VERISSIMO ',3, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(447,19347,11, 'JARDIM DA CONQUISTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(448,94498,11, 'CANDIDO PORTINARI ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(449,94455,11, 'VICENTE DE PAULO DALE COUTINHO, GEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(450,17272,11, 'GUIOMAR CABRAL ',3, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(451,205,11, 'VERA LUCIA APARECIDA RIBEIRO, PROFA. ',4, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(452,19233,11, 'EDGARD CARONE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(453,15431,11, 'ERNANI SILVA BRUNO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(454,9326,11, 'IRENE GARCIA COSTA DE SOUZA, PROFA. DRA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(455,92959,12, 'IRACEMA MARQUES DA SILVEIRA, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(456,19383,12, 'JOSE SARAMAGO ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(457,92908,12, 'CLEMENTE PASTORE, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(458,92916,12, 'ANTONIO ESTANISLAU DO AMARAL ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(459,19308,12, 'HERMES FERREIRA DE SOUZA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(460,93068,12, 'ZULMIRA CAVALHEIRO FAUSTINO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(461,19335,12, 'FEITICO DA VILA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(462,92860,12, 'MARIO MOURA E ALBUQUERQUE, BEL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(463,19466,12, 'PERIMETRAL ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(464,93076,12, 'PAULO COLOMBO PEREIRA DE QUEIROZ, DES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(465,19275,12, 'FRANCISCO REBOLO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(466,93033,12, 'MAURICIO SIMAO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(467,19348,12, 'GIANFRANCESCO GUARNIERI ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(468,93041,12, 'LEONARDO VILLAS BOAS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(469,19500,12, 'HERBERT DE SOUZA - BETINHO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(470,92924,12, 'MARIO RANGEL, CEL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(471,92975,12, 'OTONIEL MOTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(472,93050,12, 'SYNESIO ROCHA, MIN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(473,281,12, 'VERA LUCIA FUSCO BORBA, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(474,19430,12, 'CAMPO LIMPO III -LUISA ROSARIA DE OLIVEIRA DIAS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(475,19370,12, 'JARDIM MITSUTANI I - PAULO PATARRA, JORNALISTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(476,99686,12, 'RICARDO VITIELLO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(477,19712,12, 'MARIA BERENICE DOS SANTOS, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(478,16713,12, 'ANNA SILVEIRA PEDREIRA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(479,19428,12, 'SOCRATES BRASILEIRO SAMPAIO DE SOUSA VIEIRA DE OLIVEIRA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(480,99236,12, 'MODESTO SCAGLIUSI ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(481,93017,12, 'ADHEMAR DE BARROS, PREF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(482,566,12, 'TERESA MARGARIDA DA SILVA E ORTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(483,19303,12, 'CASA BLANCA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(484,93084,12, 'DE GAULLE, GEN. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(485,10154,12, 'MAURO FACCIO GONCALVES - ZACARIA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(486,87319,12, 'THEODOMIRO MONTEIRO DO AMARAL, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(487,19362,12, 'VILA DO SOL ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(488,93092,12, 'FAGUNDES VARELLA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(489,311,12, 'ANTONIO ALVES DA SILVA, SG. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(490,99112,12, 'PRACINHAS DA FEB ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(491,92878,12, 'CAROLINA RENNO RIBEIRO DE OLIVEIRA, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(492,19431,12, 'MILLOR FERNANDES, JORNALISTA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(493,19251,12, 'CASARAO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(494,19434,12, 'CAMPO LIMPO II ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(495,10162,12, 'LORENCO MANOEL SPARAPAN, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(496,19361,12, 'CANTOS DO AMANHECER ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(497,92967,12, 'LEVY DE AZEVEDO SODRE, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(498,19421,12, 'JOSE FRANCISCO CAVALCANTE, PROF ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(499,19283,12, 'JOSE BLOTA JUNIOR, DEP. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(500,19372,12, 'CHACARA SONHO AZUL ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(501,19423,12, 'M BOI MIRIM II ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(502,93009,12, 'LUIZ TENORIO DE BRITO, CEL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(503,99228,12, 'JOAO PEDRO DE CARVALHO NETO, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(504,92991,12, 'AIRTON ARANTES RIBEIRO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(505,92932,12, 'JORGE AMERICANO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(506,10146,12, 'MARIA RITA LOPES PONTES - IRMA DULCE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(507,99350,12, '22 DE MARCO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(508,12939,12, 'JOSE OLYMPIO PEREIRA FILHO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(509,19267,12, 'MARIA RITA DE CASSIA PINHEIRO SIMOES BRAGA, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(510,92886,12, 'OLIVEIRA VIANA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(511,92894,12, 'MARIO MARQUES DE OLIVEIRA, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(512,93025,12, 'PALIMERCIO DE REZENDE, CEL. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(513,19222,12, 'VEREMUNDO TOTH, DOM ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(514,18830,12, 'PAULO FREIRE, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(515,92983,12, 'PROCOPIO FERREIRA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(516,19424,12, 'MARLI FERRAZ TORRES BONFIM ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(517,10421,12, 'CYRO ALBUQUERQUE, DEP. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(518,19492,12, 'EDIVALDO DOS SANTOS DANTAS, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(519,99104,12, 'DEZOITO DO FORTE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(520,19247,12, 'TEREZINHA MOTA DE FIGUEIREDO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(521,19384,12, 'PARAISOPOLIS ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(522,19360,12, 'MARIO FITTIPALDI ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(523,19526,12, 'DONATO SUSUMU KIMURA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(524,19422,12, 'M BOI MIRIM I ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(525,92941,12, 'EUCLIDES DA CUNHA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(526,93394,13, 'TEODOMIRO TOLEDO PIZA, DES. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(527,19474,13, 'VARGEM GRANDE II ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(528,19228,13, 'JOSE PEGORARO, PE. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(529,93378,13, 'MANOEL DE ABREU, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(530,18546,13, 'DAMIAO, FREI ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(531,19406,13, 'CONSTELACAO DO INDIO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(532,19439,13, 'ALDINA ANALIA AGOSTINHA TADDEO CONDE, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(533,93335,13, 'JOAO DE DEUS CARDOSO DE MELLO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(534,93408,13, 'PAULO SETUBAL ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(535,19276,13, 'TRES LAGOS ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(536,93297,13, 'PLACIDO DE CASTRO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(537,93351,13, 'MILTON FERREIRA DE ALBUQUERQUE, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(538,19243,13, 'MARINA MELANDER COUTINHO, PROFA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(539,19254,13, 'AYRTON OLIVEIRA SAMPAIO, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(540,19263,13, 'CIDADE DUTRA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(541,19291,13, 'VARGEM GRANDE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(542,19440,13, 'GENY MARIA MUNIZ ALMEIDA KLEIN PUSSINELLI, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(543,93343,13, 'OLEGARIO MARIANO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(544,93424,13, 'MIGUEL VIEIRA FERREIRA, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(545,16501,13, 'FLORESTAN FERNANDES, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(546,19194,13, 'PEDRO GERALDO SCHUNCK ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(547,19336,13, 'VILA RUBI ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(548,93386,13, 'JOAQUIM BENTO ALVES DE LIMA NETO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(549,99791,13, 'PLINIO SALGADO ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(550,93301,13, 'HEITOR DE ANDRADE ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(551,93327,13, 'AFRANIO DE MELLO FRANCO, DR. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(552,93360,13, 'ELIZA RACHEL MACEDO DE SOUZA, PROFA. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(553,19674,13, 'JARDIM ELIANA ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(554,19305,13, 'JOAO DA SILVA ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(555,19313,13, 'MANOEL VIEIRA DE QUEIROZ FILHO ',16, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(556,19436,13, 'CARLOS FRANCISCO GASPAR ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(557,19321,13, 'LOURIVAL BRANDAO DOS SANTOS ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(558,12688,13, 'ULYSSES DA SYLVEIRA GUIMARAES ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(559,93319,13, 'ALMEIDA JUNIOR, PROF. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(560,93416,13, 'JOSE AMADEI, ENG. ',1, ' ');
INSERT INTO ETL_UES(id,ue_id, dre_id, nome, tipo_escola, data_atualizacao) VALUES(561,19496,13, 'PLINIO MARCOS ',1, ' ');
