[Environment]::SetEnvironmentVariable("Sentry__DSN", "XXX", "Machine")
[Environment]::SetEnvironmentVariable("AE_ChaveIntegracao", "XXX", "Machine")
[Environment]::SetEnvironmentVariable("AEConnection", "User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=db_appaluno;Pooling=true;", "Machine")
[Environment]::SetEnvironmentVariable("ApiEolConnection", "User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=eol_db;Pooling=true;", "Machine")
[Environment]::SetEnvironmentVariable("ChaveIntegracaoApi", "xxx", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoJasper__Hostname", "xxx", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoJasper__Password","xxx", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoJasper__Username","xxx", "Machine")
[Environment]::SetEnvironmentVariable("EolConnection", "xxx", "Machine")
[Environment]::SetEnvironmentVariable("CoreSSOConnection", "xxx", "Machine")
[Environment]::SetEnvironmentVariable("ConnectionStrings__SGP_Redis", "localhost", "Machine")
[Environment]::SetEnvironmentVariable("ConnectionStrings__SGP_Postgres", "User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=sgp_db;Pooling=true", "Machine")
[Environment]::SetEnvironmentVariable("JwtTokenSettings__IssuerSigningKey", "2A3B40C8D2215897C5EF1CC6D7D8469C687D17FDF85E675B6EBD9FBA26615B93805556652B9DDFD96CA9565C8D42EA83EF44CAC3B79AF64B343461B52FBB62EA", "Machine")
[Environment]::SetEnvironmentVariable("Logging__LogLevel__Default", "Debug", "Machine")
[Environment]::SetEnvironmentVariable("Nome_Instancia_Redis", "NovoSgp-", "Machine")
[Environment]::SetEnvironmentVariable("ExpiracaoCache__ObjetivosAprendizagem", "720", "Machine")
[Environment]::SetEnvironmentVariable("Logging__LogLevel__Microsoft", "Information", "Machine")
[Environment]::SetEnvironmentVariable("UrlApiJurema", "https://curriculo.sme.prefeitura.sp.gov.br/api/", "Machine")
[Environment]::SetEnvironmentVariable("UrlApiEOL", "https://dev-smeintegracaoapi.sme.prefeitura.sp.gov.br/api/", "Machine")
[Environment]::SetEnvironmentVariable("UrlApiAE", " https://dev-appaluno.sme.prefeitura.sp.gov.br/api/", "Machine")
[Environment]::SetEnvironmentVariable("UrlApiGithub", "https://api.github.com/", "Machine")
[Environment]::SetEnvironmentVariable("UsuarioGithub", "XXX", "Machine")
[Environment]::SetEnvironmentVariable("SenhaGithub", "XXX", "Machine")
[Environment]::SetEnvironmentVariable("UrlFrontEnd", "http://localhost:3000/", "Machine")
[Environment]::SetEnvironmentVariable("JwtTokenSettings__Audience", "Prefeitura de Sao Paulo", "Machine")
[Environment]::SetEnvironmentVariable("JwtTokenSettings__Issuer", "Novo SGP", "Machine")
[Environment]::SetEnvironmentVariable("JwtTokenSettings__ExpiresInMinutes", "720", "Machine")
[Environment]::SetEnvironmentVariable("FF_BackgroundEnabled", "true", "Machine")
[Environment]::SetEnvironmentVariable("HangfireUser_Admin", "admin:XXX", "Machine")
[Environment]::SetEnvironmentVariable("HangfireUser_Basic", "user:XXX", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoRabbit__HostName", "localhost", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoRabbit__UserName", "user", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoRabbit__Password", "bitnami", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoRabbit__Virtualhost", "dev", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoRabbitOptions__Hostname","localhost", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoRabbitOptions__LimiteDeMensagensPorExecucao","10", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoRabbitOptions__Password","bitnami", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoRabbitOptions__Username","user", "Machine")
[Environment]::SetEnvironmentVariable("ConfiguracaoRabbitOptions__Virtualhost","dev", "Machine")
[Environment]::SetEnvironmentVariable("UrlBackEnd", "http://localhost:5001/", "Machine")
[Environment]::SetEnvironmentVariable("UrlServidorRelatorios", "http://localhost:5010/", "Machine")
[Environment]::SetEnvironmentVariable("ApiKeyEolApi", "XXX", "Machine")
[Environment]::SetEnvironmentVariable("SGP_MaxRequestSizeBody", "104857600", "Machine")
[Environment]::SetEnvironmentVariable("ApiKeySr", "8f0667d1-fd48-412c-a00e-d43d61c4fa02", "Machine")
