alter table relatorio_semestral rename to relatorio_semestral_turma_pap;

alter table relatorio_semestral_aluno rename to relatorio_semestral_pap_aluno;
alter table relatorio_semestral_pap_aluno rename column relatorio_semestral_id to relatorio_semestral_turma_pap_id;

alter table relatorio_semestral_aluno_secao rename to relatorio_semestral_pap_aluno_secao;
alter table relatorio_semestral_pap_aluno_secao rename column relatorio_semestral_aluno_id to relatorio_semestral_pap_aluno_id;
alter table relatorio_semestral_pap_aluno_secao rename column secao_relatorio_semestral_id to secao_relatorio_semestral_pap_id;

alter table secao_relatorio_semestral rename to secao_relatorio_semestral_pap;
