update componente_curricular set descricao_sgp = 'Investigação Científica e Processos Matemáticos (Física)' where id = 	1314;
update componente_curricular set descricao_sgp = 'LEM - Língua Inglesa' where id = 	1328;
update componente_curricular set descricao_sgp = 'Língua Portuguesa - Formação para Estudos e Aprofundamento' where id = 	1329;
update componente_curricular set descricao_sgp = 'LEM - Língua Inglesa - Formação para Estudos e Aprofundamento' where id = 	1330;
update componente_curricular set descricao_sgp = 'Matemática - Formação para Estudos e Aprofundamento' where id = 	1331;
update componente_curricular set descricao_sgp = 'Geografia - Formação para Estudos e Aprofundamento' where id = 	1332;
update componente_curricular set descricao_sgp = 'História - Formação para Estudos e Aprofundamento' where id = 	1333;
update componente_curricular set descricao_sgp = 'Biologia - Formação para Estudos e Aprofundamento' where id = 	1334;
update componente_curricular set descricao_sgp = 'Química - Formação para Estudos e Aprofundamento' where id = 	1335;
update componente_curricular set descricao_sgp = 'Física - Formação para Estudos e Aprofundamento' where id = 	1336;
update componente_curricular set descricao_sgp = 'Características dos seres vivos e as teorias unificadoras da Biologia' where id = 	1337;
update componente_curricular set descricao_sgp = 'Investigações do mundo físico e químico' where id = 	1338;
update componente_curricular set descricao_sgp = 'Projeto de vida' where id = 	1339;
update componente_curricular set descricao_sgp = 'Expressões Culturais e Artísticas' where id = 	1340;
update componente_curricular set descricao_sgp = 'Língua, Literatura e Cultura dos países de Língua Espanhola' where id = 	1346;
update componente_curricular set descricao_sgp = 'Sala de Leitura' where id = 	1347;
update componente_curricular set descricao_sgp = 'Tecnologias para Aprendizagem' where id = 	1348;
update componente_curricular set descricao_sgp = 'Tecnologias para Aprendizagem' where id = 	1349;
update componente_curricular set descricao_sgp = 'Projeto de vida' where id = 	1350;
update componente_curricular set descricao_sgp = 'Investigação Científica e Processos Matemáticos (Química)' where id = 	1351;
update componente_curricular set descricao_sgp = 'Formação do Mundo Multipolar' where id = 	1352;
update componente_curricular set descricao_sgp = 'Trajetória dos Direitos Humanos' where id = 	1353;
update componente_curricular set descricao_sgp = 'Sociedade, Cultura e Interculturalismo' where id = 	1354;
update componente_curricular set descricao_sgp = 'Língua, Literatura e Cultura dos países de Língua Inglesa' where id = 	1355;
update componente_curricular set descricao_sgp = 'Língua e Literatura de Língua Portuguesa' where id = 	1356;
update componente_curricular set descricao_sgp = 'Investigação Científica e Processos Matemáticos (Química)' where id = 	1357;
update componente_curricular set descricao_sgp = 'Sala de Leitura' where id = 	1358;
update componente_curricular set descricao_sgp = 'Tecnologias para Aprendizagem' where id = 	1359;
update componente_curricular set descricao_sgp = 'Geografia - Formação para Estudos e Aprofundamento' where id = 	1414;
update componente_curricular set descricao_sgp = 'História - Formação para Estudos e Aprofundamento' where id = 	1415;
update componente_curricular set descricao_sgp = 'Biologia - Formação para Estudos e Aprofundamento' where id = 	1416;
update componente_curricular set descricao_sgp = 'Língua e Literatura de Língua Portuguesa' where id = 	1417;
update componente_curricular set descricao_sgp = 'Língua, Literatura e Cultura dos países de Língua Inglesa' where id = 	1418;
update componente_curricular set descricao_sgp = 'Expressões Culturais e Artísticas (Educação Física)' where id = 	1419;
update componente_curricular set descricao_sgp = 'Formação do Mundo Multipolar (Geografia)' where id = 	1420;
update componente_curricular set descricao_sgp = 'Trajetória dos Direitos Humanos (Filosofia)' where id = 	1421;
update componente_curricular set descricao_sgp = 'Trajetória dos Direitos Humanos (Sociologia)' where id = 	1422;
update componente_curricular set descricao_sgp = 'Sociedade, Cultura e Interculturalismo (História)' where id = 	1423;
update componente_curricular set descricao_sgp = 'Sociedade, Cultura e Interculturalismo (Geografia)' where id = 	1424;
update componente_curricular set descricao_sgp = 'Formação do Mundo Multipolar (História)' where id = 	1425;
update componente_curricular set descricao_sgp = 'Sociedade, Cultura e Interculturalismo (Filosofia)' where id = 	1426;
update componente_curricular set descricao_sgp = 'Sociedade, Cultura e Interculturalismo (Sociologia)' where id = 	1427;
update componente_curricular set descricao_sgp = 'Investigações Matemáticas' where id = 	1428;
update componente_curricular set descricao_sgp = 'Investigações do mundo físico e químico (Física)' where id = 	1429;
update componente_curricular set descricao_sgp = 'Investigações do mundo físico e químico (Química)' where id = 	1430;
update componente_curricular set descricao_sgp = 'Características dos seres vivos e as teorias unificadoras da Biologia (Química)' where id = 	1431;
update componente_curricular set descricao_sgp = 'Libras - Formação para Estudos e Aprofundamento' where id = 	1432;
