CREATE TABLE public.conselho_classe_aluno_turma_complementar (
	conselho_classe_aluno_id int8 NOT NULL,
	turma_id int8 NOT NULL,
	
	CONSTRAINT conselho_classe_aluno_turma_complementar_pk PRIMARY KEY (conselho_classe_aluno_id, turma_id)
);
CREATE INDEX conselho_classe_aluno_turma_complementar_conselho_classe_aluno_idx ON public.conselho_classe_aluno_turma_complementar USING btree (conselho_classe_aluno_id);
CREATE INDEX conselho_classe_aluno_turma_complementar_turma_id_idx ON public.conselho_classe_aluno_turma_complementar USING btree (turma_id);


ALTER TABLE public.conselho_classe_aluno_turma_complementar ADD CONSTRAINT conselho_classe_aluno_turma_complementar_conselho_classe_aluno_id_fk FOREIGN KEY (conselho_classe_aluno_id) REFERENCES conselho_classe_aluno(id);
ALTER TABLE public.conselho_classe_aluno_turma_complementar ADD CONSTRAINT conselho_classe_aluno_turma_complementar_turma_id_fk FOREIGN KEY (turma_id) REFERENCES turma(id);