/********************* A1 *********************/
insert into grade(nome, criado_em, criado_por, criado_rf) values('Fundamental regular 2 turnos diurnos', NOW(), 'Carga', 'Carga');
insert into grade_filtro(grade_id, tipo_escola, modalidade, duracao_turno, criado_em, criado_por, criado_rf) values
-- EMEF - Fundamental - Duracao 5
	(currval('grade_id_seq'::regclass), 1, 5, 5, NOW(), 'Carga', 'Carga'),
-- EMEFM - Fundamental - Duracao 5
	(currval('grade_id_seq'::regclass), 3, 5, 5, NOW(), 'Carga', 'Carga'),
-- CEU EMEF - Fundamental - Duracao 5
	(currval('grade_id_seq'::regclass), 16, 5, 5, NOW(), 'Carga', 'Carga');


insert into grade_disciplina(grade_id, componente_curricular_id, ano, quantidade_aulas, criado_em, criado_por, criado_rf) values 
-- Lingua Portuguesa
	(currval('grade_id_seq'::regclass), 138, 1, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 2, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 3, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 4, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 5, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 6, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 7, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 8, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 9, 5, NOW(), 'Carga', 'Carga'),
-- Arte	
	(currval('grade_id_seq'::regclass), 139, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 6, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 7, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 8, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 9, 2, NOW(), 'Carga', 'Carga'),
-- Ed.Fisica	
	(currval('grade_id_seq'::regclass), 6, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 9, 3, NOW(), 'Carga', 'Carga'),
-- Matemática	
	(currval('grade_id_seq'::regclass), 2, 1, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 2, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 3, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 4, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 5, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 6, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 7, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 8, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 9, 5, NOW(), 'Carga', 'Carga'),
-- Ciências	
	(currval('grade_id_seq'::regclass), 89, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 6, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 7, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 8, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 9, 4, NOW(), 'Carga', 'Carga'),
-- Geografia	
	(currval('grade_id_seq'::regclass), 8, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 8, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 9, 4, NOW(), 'Carga', 'Carga'),
-- Historia	
	(currval('grade_id_seq'::regclass), 7, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 6, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 7, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 9, 3, NOW(), 'Carga', 'Carga'),
-- Lingua Inglesa	
	(currval('grade_id_seq'::regclass), 9, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 6, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 7, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 8, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 9, 2, NOW(), 'Carga', 'Carga'),
-- Sala de Leitura	
	(currval('grade_id_seq'::regclass), 1061, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 6, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 7, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 8, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 9, 1, NOW(), 'Carga', 'Carga'),
-- Informatica Educativa	
	(currval('grade_id_seq'::regclass), 1060, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 6, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 7, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 8, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 9, 1, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Projetos	
	(currval('grade_id_seq'::regclass), 1111, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1111, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1111, 6, 4, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Lingua Inglesa
	(currval('grade_id_seq'::regclass), 1106, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1106, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1106, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1106, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1106, 5, 2, NOW(), 'Carga', 'Carga');

/********************* A2 *********************/
insert into grade(nome, criado_em, criado_por, criado_rf) values('Fundamental regular 3 turnos diurnos, quatro turnos e cursos noturnos', NOW(), 'Carga', 'Carga');
-- EMEF - Fundamental - Duracao 4
insert into grade_filtro(grade_id, tipo_escola, modalidade, duracao_turno, criado_em, criado_por, criado_rf) values
	(currval('grade_id_seq'::regclass), 1, 5, 4, NOW(), 'Carga', 'Carga'),
-- EMEFM - Fundamental - Duracao 4
	(currval('grade_id_seq'::regclass), 3, 5, 4, NOW(), 'Carga', 'Carga'),
-- CEU EMEF - Fundamental - Duracao 4
	(currval('grade_id_seq'::regclass), 16, 5, 4, NOW(), 'Carga', 'Carga');

insert into grade_disciplina(grade_id, componente_curricular_id, ano, quantidade_aulas, criado_em, criado_por, criado_rf) values 
-- Lingua Portuguesa
	(currval('grade_id_seq'::regclass), 138, 1, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 2, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 3, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 4, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 5, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 6, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 7, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 8, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 9, 5, NOW(), 'Carga', 'Carga'),
-- Arte	
	(currval('grade_id_seq'::regclass), 139, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 6, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 7, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 8, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 9, 2, NOW(), 'Carga', 'Carga'),
-- Ed.Fisica	
	(currval('grade_id_seq'::regclass), 6, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 9, 3, NOW(), 'Carga', 'Carga'),
-- Matemática	
	(currval('grade_id_seq'::regclass), 2, 1, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 2, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 3, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 4, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 5, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 6, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 7, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 8, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 9, 5, NOW(), 'Carga', 'Carga'),
-- Ciências	
	(currval('grade_id_seq'::regclass), 89, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 6, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 7, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 8, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 9, 4, NOW(), 'Carga', 'Carga'),
-- Geografia	
	(currval('grade_id_seq'::regclass), 8, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 8, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 9, 4, NOW(), 'Carga', 'Carga'),
-- Historia	
	(currval('grade_id_seq'::regclass), 7, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 6, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 7, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 9, 3, NOW(), 'Carga', 'Carga'),
-- Lingua Inglesa	
	(currval('grade_id_seq'::regclass), 9, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 6, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 7, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 8, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 9, 2, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Projetos	
	(currval('grade_id_seq'::regclass), 1111, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1111, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1111, 6, 4, NOW(), 'Carga', 'Carga'),
-- Sala de Leitura	
	(currval('grade_id_seq'::regclass), 1061, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 6, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 7, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 8, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 9, 1, NOW(), 'Carga', 'Carga'),
-- Informatica Educativa	
	(currval('grade_id_seq'::regclass), 1060, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 6, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 7, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 8, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 9, 1, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Lingua Inglesa
	(currval('grade_id_seq'::regclass), 1106, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1106, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1106, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1106, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1106, 5, 2, NOW(), 'Carga', 'Carga');

/********************* B *********************/
insert into grade(nome, criado_em, criado_por, criado_rf) values('Ensino fundamental EJA', NOW(), 'Carga', 'Carga');
-- EMEF - EJA - Duracao 4
insert into grade_filtro(grade_id, tipo_escola, modalidade, duracao_turno, criado_em, criado_por, criado_rf) values
	(currval('grade_id_seq'::regclass), 1, 3, 4, NOW(), 'Carga', 'Carga'),
-- EMEFM - EJA - Duracao 4
	(currval('grade_id_seq'::regclass), 3, 3, 4, NOW(), 'Carga', 'Carga'),
-- CEU EMEF - EJA - Duracao 4
	(currval('grade_id_seq'::regclass), 16, 3, 4, NOW(), 'Carga', 'Carga');

insert into grade_disciplina(grade_id, componente_curricular_id, ano, quantidade_aulas, criado_em, criado_por, criado_rf) values 
-- Lingua Portuguesa
	(currval('grade_id_seq'::regclass), 138, 1, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 2, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 3, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 4, 5, NOW(), 'Carga', 'Carga'),
-- Arte	
	(currval('grade_id_seq'::regclass), 139, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 4, 2, NOW(), 'Carga', 'Carga'),
-- Ed.Fisica	
	(currval('grade_id_seq'::regclass), 6, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 4, 3, NOW(), 'Carga', 'Carga'),
-- Matemática	
	(currval('grade_id_seq'::regclass), 2, 1, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 2, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 3, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 4, 5, NOW(), 'Carga', 'Carga'),
-- Ciências	
	(currval('grade_id_seq'::regclass), 89, 1, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 2, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 3, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 4, 4, NOW(), 'Carga', 'Carga'),
-- Geografia	
	(currval('grade_id_seq'::regclass), 8, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 2, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 4, 4, NOW(), 'Carga', 'Carga'),
-- Historia	
	(currval('grade_id_seq'::regclass), 7, 1, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 3, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 4, 3, NOW(), 'Carga', 'Carga'),
-- Lingua Inglesa	
	(currval('grade_id_seq'::regclass), 9, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 4, 2, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Sala de Leitura	
	(currval('grade_id_seq'::regclass), 1061, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 4, 1, NOW(), 'Carga', 'Carga'),
-- Informatica Educativa	
	(currval('grade_id_seq'::regclass), 1060, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 4, 1, NOW(), 'Carga', 'Carga');

/********************* C1 *********************/
insert into grade(nome, criado_em, criado_por, criado_rf) values('Ensino fundamental - EMEBs diurno', NOW(), 'Carga', 'Carga');
-- EMEBs - Fundamental - Duracao 5
insert into grade_filtro(grade_id, tipo_escola, modalidade, duracao_turno, criado_em, criado_por, criado_rf) values
	(currval('grade_id_seq'::regclass), 4, 5, 5, NOW(), 'Carga', 'Carga');

insert into grade_disciplina(grade_id, componente_curricular_id, ano, quantidade_aulas, criado_em, criado_por, criado_rf) values 
-- Lingua Portuguesa
	(currval('grade_id_seq'::regclass), 138, 1, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 2, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 3, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 4, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 5, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 6, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 7, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 8, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 9, 6, NOW(), 'Carga', 'Carga'),
-- Arte	
	(currval('grade_id_seq'::regclass), 139, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 6, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 7, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 8, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 9, 2, NOW(), 'Carga', 'Carga'),
-- Ed.Fisica	
	(currval('grade_id_seq'::regclass), 6, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 9, 3, NOW(), 'Carga', 'Carga'),
-- Matemática	
	(currval('grade_id_seq'::regclass), 2, 1, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 2, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 3, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 4, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 5, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 6, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 7, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 8, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 9, 5, NOW(), 'Carga', 'Carga'),
-- Ciências	
	(currval('grade_id_seq'::regclass), 89, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 9, 3, NOW(), 'Carga', 'Carga'),
-- Geografia	
	(currval('grade_id_seq'::regclass), 8, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 9, 3, NOW(), 'Carga', 'Carga'),
-- Historia	
	(currval('grade_id_seq'::regclass), 7, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 9, 3, NOW(), 'Carga', 'Carga'),
-- Libras
	(currval('grade_id_seq'::regclass), 218, 1, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 2, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 3, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 4, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 5, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 9, 3, NOW(), 'Carga', 'Carga'),
-- Sala de Leitura	
	(currval('grade_id_seq'::regclass), 1061, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 6, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 7, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 8, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 9, 1, NOW(), 'Carga', 'Carga'),
-- Informatica Educativa	
	(currval('grade_id_seq'::regclass), 1060, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 6, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 7, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 8, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 9, 1, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Projetos	
	(currval('grade_id_seq'::regclass), 1111, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1111, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1111, 6, 3, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Libras
	(currval('grade_id_seq'::regclass), 1116, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 6, 1, NOW(), 'Carga', 'Carga');

/********************* C2 *********************/
insert into grade(nome, criado_em, criado_por, criado_rf) values('Ensino fundamental - EMEBs noturno', NOW(), 'Carga', 'Carga');
-- EMEBs - Fundamental - Duracao 4
insert into grade_filtro(grade_id, tipo_escola, modalidade, duracao_turno, criado_em, criado_por, criado_rf) values 
	(currval('grade_id_seq'::regclass), 4, 5, 4, NOW(), 'Carga', 'Carga');

insert into grade_disciplina(grade_id, componente_curricular_id, ano, quantidade_aulas, criado_em, criado_por, criado_rf) values 
-- Lingua Portuguesa
	(currval('grade_id_seq'::regclass), 138, 1, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 2, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 3, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 4, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 5, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 6, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 7, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 8, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 9, 6, NOW(), 'Carga', 'Carga'),
-- Arte	
	(currval('grade_id_seq'::regclass), 139, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 6, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 7, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 8, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 9, 2, NOW(), 'Carga', 'Carga'),
-- Ed.Fisica	
	(currval('grade_id_seq'::regclass), 6, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 9, 3, NOW(), 'Carga', 'Carga'),
-- Matemática	
	(currval('grade_id_seq'::regclass), 2, 1, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 2, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 3, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 4, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 5, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 6, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 7, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 8, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 9, 5, NOW(), 'Carga', 'Carga'),
-- Ciências	
	(currval('grade_id_seq'::regclass), 89, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 9, 3, NOW(), 'Carga', 'Carga'),
-- Geografia	
	(currval('grade_id_seq'::regclass), 8, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 9, 3, NOW(), 'Carga', 'Carga'),
-- Historia	
	(currval('grade_id_seq'::regclass), 7, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 9, 3, NOW(), 'Carga', 'Carga'),
-- Libras
	(currval('grade_id_seq'::regclass), 218, 1, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 2, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 3, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 4, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 5, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 9, 3, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Projetos	
	(currval('grade_id_seq'::regclass), 1111, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1111, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1111, 6, 3, NOW(), 'Carga', 'Carga'),
-- Sala de Leitura	
	(currval('grade_id_seq'::regclass), 1061, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 6, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 7, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 8, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 9, 1, NOW(), 'Carga', 'Carga'),
-- Informatica Educativa	
	(currval('grade_id_seq'::regclass), 1060, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 6, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 7, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 8, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 9, 1, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Libras
	(currval('grade_id_seq'::regclass), 1116, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 6, 1, NOW(), 'Carga', 'Carga');

/********************* D *********************/
insert into grade(nome, criado_em, criado_por, criado_rf) values('Ensino fundamental EJA na EMEBs', NOW(), 'Carga', 'Carga');
-- EMEBs - EJA - Duracao 4
insert into grade_filtro(grade_id, tipo_escola, modalidade, duracao_turno, criado_em, criado_por, criado_rf) values 
	(currval('grade_id_seq'::regclass), 4, 3, 4, NOW(), 'Carga', 'Carga');

insert into grade_disciplina(grade_id, componente_curricular_id, ano, quantidade_aulas, criado_em, criado_por, criado_rf) values 
-- Lingua Portuguesa
	(currval('grade_id_seq'::regclass), 138, 1, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 2, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 3, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 4, 6, NOW(), 'Carga', 'Carga'),
-- Arte	
	(currval('grade_id_seq'::regclass), 139, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 4, 2, NOW(), 'Carga', 'Carga'),
-- Ed.Fisica	
	(currval('grade_id_seq'::regclass), 6, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 4, 3, NOW(), 'Carga', 'Carga'),
-- Matemática	
	(currval('grade_id_seq'::regclass), 2, 1, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 2, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 3, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 4, 5, NOW(), 'Carga', 'Carga'),
-- Ciências	
	(currval('grade_id_seq'::regclass), 89, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 4, 3, NOW(), 'Carga', 'Carga'),
-- Geografia	
	(currval('grade_id_seq'::regclass), 8, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 4, 3, NOW(), 'Carga', 'Carga'),
-- Historia	
	(currval('grade_id_seq'::regclass), 7, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 4, 3, NOW(), 'Carga', 'Carga'),
-- Libras	
	(currval('grade_id_seq'::regclass), 218, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 4, 3, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Sala de Leitura	
	(currval('grade_id_seq'::regclass), 1061, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 4, 1, NOW(), 'Carga', 'Carga'),
-- Informatica Educativa	
	(currval('grade_id_seq'::regclass), 1060, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 2, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 3, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 4, 1, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Libras
	(currval('grade_id_seq'::regclass), 1116, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 2, 2, NOW(), 'Carga', 'Carga');

/********************* E *********************/
insert into grade(nome, criado_em, criado_por, criado_rf) values('Ensino medio', NOW(), 'Carga', 'Carga');
-- EMEFM - Medio - Duracao 5
insert into grade_filtro(grade_id, tipo_escola, modalidade, duracao_turno, criado_em, criado_por, criado_rf) values 
	(currval('grade_id_seq'::regclass), 3, 6, 5, NOW(), 'Carga', 'Carga');

insert into grade_disciplina(grade_id, componente_curricular_id, ano, quantidade_aulas, criado_em, criado_por, criado_rf) values 
-- Lingua Portuguesa
	(currval('grade_id_seq'::regclass), 138, 1, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 3, 4, NOW(), 'Carga', 'Carga'),
-- Arte	
	(currval('grade_id_seq'::regclass), 139, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 3, 2, NOW(), 'Carga', 'Carga'),
-- Ed.Fisica	
	(currval('grade_id_seq'::regclass), 6, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 3, 3, NOW(), 'Carga', 'Carga'),
-- Matemática	
	(currval('grade_id_seq'::regclass), 2, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 3, 3, NOW(), 'Carga', 'Carga'),
-- Física
	(currval('grade_id_seq'::regclass), 51, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 51, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 51, 3, 2, NOW(), 'Carga', 'Carga'),
-- Química
	(currval('grade_id_seq'::regclass), 52, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 52, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 52, 3, 2, NOW(), 'Carga', 'Carga'),
-- Biologia
	(currval('grade_id_seq'::regclass), 53, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 53, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 53, 3, 2, NOW(), 'Carga', 'Carga'),
-- Historia	
	(currval('grade_id_seq'::regclass), 7, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 3, 2, NOW(), 'Carga', 'Carga'),
-- Geografia	
	(currval('grade_id_seq'::regclass), 8, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 3, 2, NOW(), 'Carga', 'Carga'),
-- Inglês
	(currval('grade_id_seq'::regclass), 9, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 3, 2, NOW(), 'Carga', 'Carga'),
-- Espanhol
	(currval('grade_id_seq'::regclass), 537, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 537, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 537, 3, 2, NOW(), 'Carga', 'Carga'),
-- Filosofia
	(currval('grade_id_seq'::regclass), 98, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 98, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 98, 3, 1, NOW(), 'Carga', 'Carga'),
-- Sociologia
	(currval('grade_id_seq'::regclass), 103, 1, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 103, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 103, 3, 1, NOW(), 'Carga', 'Carga');

/********************* F1 *********************/
insert into grade(nome, criado_em, criado_por, criado_rf) values('São Paulo integral (Anexo I)', NOW(), 'Carga', 'Carga');
-- EMEF - Fundamental - Duracao 7
insert into grade_filtro(grade_id, tipo_escola, modalidade, duracao_turno, criado_em, criado_por, criado_rf) values 
	(currval('grade_id_seq'::regclass), 1, 5, 7, NOW(), 'Carga', 'Carga'),
-- EMEFM - Fundamental - Duracao 7
	(currval('grade_id_seq'::regclass), 3, 5, 7, NOW(), 'Carga', 'Carga'),
-- CEU EMEF - Fundamental - Duracao 7
	(currval('grade_id_seq'::regclass), 16, 5, 7, NOW(), 'Carga', 'Carga');


insert into grade_disciplina(grade_id, componente_curricular_id, ano, quantidade_aulas, criado_em, criado_por, criado_rf) values 
-- Lingua Portuguesa
	(currval('grade_id_seq'::regclass), 138, 1, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 2, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 3, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 4, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 5, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 6, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 7, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 8, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 9, 5, NOW(), 'Carga', 'Carga'),
-- Arte	
	(currval('grade_id_seq'::regclass), 139, 1, 1+1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 2, 1+1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 3, 1+1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 6, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 7, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 8, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 9, 2, NOW(), 'Carga', 'Carga'),
-- Ed.Fisica	
	(currval('grade_id_seq'::regclass), 6, 1, 2+1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 2, 2+1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 3, 2+1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 9, 3, NOW(), 'Carga', 'Carga'),
-- Matemática	
	(currval('grade_id_seq'::regclass), 2, 1, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 2, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 3, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 4, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 5, 7, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 6, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 7, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 8, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 9, 5, NOW(), 'Carga', 'Carga'),
-- Ciências	
	(currval('grade_id_seq'::regclass), 89, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 6, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 7, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 8, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 9, 4, NOW(), 'Carga', 'Carga'),
-- Geografia	
	(currval('grade_id_seq'::regclass), 8, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 8, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 9, 4, NOW(), 'Carga', 'Carga'),
-- Historia	
	(currval('grade_id_seq'::regclass), 7, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 6, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 7, 4, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 9, 3, NOW(), 'Carga', 'Carga'),
-- Lingua Inglesa	
	(currval('grade_id_seq'::regclass), 9, 1, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 6, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 7, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 8, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 9, 9, 2, NOW(), 'Carga', 'Carga'),
-- Sala de Leitura	
	(currval('grade_id_seq'::regclass), 1061, 1, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 2, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 3, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 4, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 5, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 6, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 7, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 8, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 9, 1+2, NOW(), 'Carga', 'Carga'),
-- Informatica Educativa	
	(currval('grade_id_seq'::regclass), 1060, 1, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 2, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 3, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 4, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 5, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 6, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 7, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 8, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 9, 1+2, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Projetos	
	(currval('grade_id_seq'::regclass), 1111, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1111, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1111, 6, 4, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 1
	(currval('grade_id_seq'::regclass), 1214, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 2
	(currval('grade_id_seq'::regclass), 1215, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 3
	(currval('grade_id_seq'::regclass), 1216, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 4
	(currval('grade_id_seq'::regclass), 1217, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 5
	(currval('grade_id_seq'::regclass), 1218, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 6
	(currval('grade_id_seq'::regclass), 1219, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 7
	(currval('grade_id_seq'::regclass), 1220, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 8
	(currval('grade_id_seq'::regclass), 1221, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 9
	(currval('grade_id_seq'::regclass), 1222, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 10
	(currval('grade_id_seq'::regclass), 1223, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 9, 10, NOW(), 'Carga', 'Carga');

/********************* F2 *********************/
insert into grade(nome, criado_em, criado_por, criado_rf) values('São Paulo integral (Anexo II)', NOW(), 'Carga', 'Carga');
-- EMEBs - Fundamental - Duracao 7
insert into grade_filtro(grade_id, tipo_escola, modalidade, duracao_turno, criado_em, criado_por, criado_rf) values 
	(currval('grade_id_seq'::regclass), 4, 5, 7, NOW(), 'Carga', 'Carga');


insert into grade_disciplina(grade_id, componente_curricular_id, ano, quantidade_aulas, criado_em, criado_por, criado_rf) values 
-- Lingua Portuguesa
	(currval('grade_id_seq'::regclass), 138, 1, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 2, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 3, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 4, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 5, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 6, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 7, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 8, 6, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 138, 9, 6, NOW(), 'Carga', 'Carga'),
-- Arte	
	(currval('grade_id_seq'::regclass), 139, 1, 1+1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 2, 1+1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 3, 1+1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 5, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 6, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 7, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 8, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 139, 9, 2, NOW(), 'Carga', 'Carga'),
-- Ed.Fisica	
	(currval('grade_id_seq'::regclass), 6, 1, 2+1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 2, 2+1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 3, 2+1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 6, 9, 3, NOW(), 'Carga', 'Carga'),
-- Matemática	
	(currval('grade_id_seq'::regclass), 2, 1, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 2, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 3, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 4, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 5, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 6, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 7, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 8, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 2, 9, 5, NOW(), 'Carga', 'Carga'),
-- Ciências	
	(currval('grade_id_seq'::regclass), 89, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 89, 9, 3, NOW(), 'Carga', 'Carga'),
-- Geografia	
	(currval('grade_id_seq'::regclass), 8, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 8, 9, 3, NOW(), 'Carga', 'Carga'),
-- Historia	
	(currval('grade_id_seq'::regclass), 7, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 2, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 3, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 4, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 5, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 7, 9, 3, NOW(), 'Carga', 'Carga'),
-- Libras	
	(currval('grade_id_seq'::regclass), 218, 1, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 2, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 3, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 4, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 5, 5, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 6, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 7, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 8, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 218, 9, 3, NOW(), 'Carga', 'Carga'),
-- Sala de Leitura	
	(currval('grade_id_seq'::regclass), 1061, 1, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 2, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 3, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 4, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 5, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 6, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 7, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 8, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1061, 9, 1+2, NOW(), 'Carga', 'Carga'),
-- Informatica Educativa	
	(currval('grade_id_seq'::regclass), 1060, 1, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 2, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 3, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 4, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 5, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 6, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 7, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 8, 1+2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1060, 9, 1+2, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Projetos	
	(currval('grade_id_seq'::regclass), 1111, 4, 1, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1111, 5, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1111, 6, 3, NOW(), 'Carga', 'Carga'),
-- Docencia Compartilhada - Projetos	
	(currval('grade_id_seq'::regclass), 1116, 1, 3, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 2, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 3, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 4, 2, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1116, 5, 1, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 1
	(currval('grade_id_seq'::regclass), 1214, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1214, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 2
	(currval('grade_id_seq'::regclass), 1215, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1215, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 3
	(currval('grade_id_seq'::regclass), 1216, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1216, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 4
	(currval('grade_id_seq'::regclass), 1217, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1217, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 5
	(currval('grade_id_seq'::regclass), 1218, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1218, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 6
	(currval('grade_id_seq'::regclass), 1219, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1219, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 7
	(currval('grade_id_seq'::regclass), 1220, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1220, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 8
	(currval('grade_id_seq'::regclass), 1221, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1221, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 9
	(currval('grade_id_seq'::regclass), 1222, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1222, 9, 10, NOW(), 'Carga', 'Carga'),
-- Experiências Pedagógicas 10
	(currval('grade_id_seq'::regclass), 1223, 1, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 2, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 3, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 4, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 5, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 6, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 7, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 8, 10, NOW(), 'Carga', 'Carga'),
	(currval('grade_id_seq'::regclass), 1223, 9, 10, NOW(), 'Carga', 'Carga');
