CREATE table if not exists public.consolidacao_produtividade_frequencia (
	id int8 NOT NULL GENERATED ALWAYS AS IDENTITY,
	turma_id varchar(15) not null,
	ue_id varchar(15) not null,
	dre_id varchar(15) not null,
	dre_desc varchar(100) not null,
	ue_desc varchar(100) not null,
	turma_desc varchar(100) not null,
	professor_nm varchar(100) not null,
	professor_rf varchar(25) not null,
	bimestre int4 not null,
	modalidade_codigo int4 not null,
	data_aula date not null,
	data_reg_freq date not null,
	dif_data_aula_reg_freq int4 not null,
	ano_letivo int4 not null,
	componente_curricular_id varchar(15) not null,
	componente_curricular_nm varchar(100) not null,
	criado_em timestamp NOT NULL,
	criado_por varchar(200) NOT NULL,
	alterado_em timestamp NULL,
	alterado_por varchar(200) NULL,
	criado_rf varchar(200) NOT NULL,
	alterado_rf varchar(200) NULL,
	CONSTRAINT consolidacao_produtividade_frequencia_pk PRIMARY KEY (id)
);                  