<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AspNetCore.HealthChecks.Elasticsearch" Version="6.0.0" />
      <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="6.0.2" />
      <PackageReference Include="AspNetCore.HealthChecks.Prometheus.Metrics" Version="6.0.0" />
      <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" Version="6.0.0" />
      <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="6.0.0" />
      <PackageReference Include="AspNetCore.HealthChecks.UI" Version="6.0.1" />
      <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="5.0.1" />
      <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="5.0.1" />
      <PackageReference Include="AspNetCore.HealthChecks.UI.PostgreSQL.Storage" Version="5.0.1" />
      <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="6.0.0" />
      <PackageReference Include="Npgsql" Version="6.0.13" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SME.SGP.Dados.Cache\SME.SGP.Dados.Cache.csproj" />
    </ItemGroup>

</Project>
