USE [Manutencao]
GO


-- SELECT DE SAÍDA (PARA EXPORTAÇÃO NO POSTGRESQL)
SELECT DISTINCT
       [TURMA_ID],
       [PERIODO_ESCOLAR_ID],
       MIN(CONVERT(DATETIME,CONVERT(VARCHAR, [CRIADO_EM], 120))) AS [CRIADO_EM],
 	   MAX(CONVERT(DATETIME,CONVERT(VARCHAR, [ALTERADO_EM], 120))) AS [ALTERADO_EM],
	   [DISCIPLINA_ID],
       [ALUNO_CODIGO],
       CASE WHEN ISNUMERIC(REPLACE([NOTA],'.',',')) = 1 THEN REPLACE([NOTA],'.',',')
		                                                ELSE NULL
	   END AS [NOTA],
	   [SINTESE_ID],
	   [CONCEITO_ID],
       MIN(CONVERT(DATETIME,CONVERT(VARCHAR, [CRIADO_EM_CC], 120))) AS [CRIADO_EM_CC],
 	   MAX(CONVERT(DATETIME,CONVERT(VARCHAR, [ALTERADO_EM_CC], 120))) AS [ALTERADO_EM_CC],
	   [RECOMENDACOES_ALUNO],
	   [RECOMENDACOES_FAMILIA],
	   [ANOTACOES_PEDAGOGICAS],
       CASE WHEN ISNUMERIC(REPLACE([NOTACC],'.',',')) = 1 THEN REPLACE([NOTACC],'.',',')
		                                                  ELSE [NOTACC]
	   END AS [NOTACC],
	   [JUSTIFICATIVA],
	   [PARECER],
	   [SERIE],
	   [CONCEITO_ID_CC]
  FROM [Manutencao].[dbo].[ETL_SGP_Fechamento_CC]
  GROUP BY
       [TURMA_ID],
       [PERIODO_ESCOLAR_ID],
       [DISCIPLINA_ID],
       [ALUNO_CODIGO],
       [NOTA], 
	   [SINTESE_ID],
   	   [CONCEITO_ID],
	   [RECOMENDACOES_ALUNO],
	   [RECOMENDACOES_FAMILIA],
	   [ANOTACOES_PEDAGOGICAS],
	   [NOTACC],
	   [JUSTIFICATIVA],
	   [PARECER],
	   [SERIE],
	   [CONCEITO_ID_CC]
 ORDER BY 
       [TURMA_ID],
       [ALUNO_CODIGO],
       [DISCIPLINA_ID],
       [PERIODO_ESCOLAR_ID]
GO

