USE [Manutencao]
GO


-- SELECT DE SAÍDA (PARA EXPORTAÇÃO NO POSTGRESQL)
SELECT DISTINCT
       [TURMA_ID],
       [PERIODO_ESCOLAR_ID],
       MIN(CONVERT(DATETIME,CONVERT(VARCHAR, [CRIADO_EM], 120))) AS [CRIADO_EM],
 	   MAX(CONVERT(DATETIME,CONVERT(VARCHAR, [ALTERADO_EM], 120))) AS [ALTERADO_EM],
	   [DISCIPLINA_ID],
       [ALUNO_CODIGO],
       CASE WHEN ISNUMERIC(REPLACE([NOTA],'.',',')) = 1 THEN REPLACE([NOTA],'.',',')
		                                                ELSE NULL
	   END AS [NOTA],
	   [SINTESE_ID],
	   [CONCEITO_ID]
  FROM [Manutencao].[dbo].[ETL_SGP_Fechamento]
  GROUP BY
       [TURMA_ID],
       [PERIODO_ESCOLAR_ID],
       [DISCIPLINA_ID],
       [ALUNO_CODIGO],
       [NOTA], 
	   [SINTESE_ID],
   	   [CONCEITO_ID]
 ORDER BY 
       [TURMA_ID],
       [ALUNO_CODIGO],
       [DISCIPLINA_ID],
       [PERIODO_ESCOLAR_ID]
GO
